version: 2

build:
  os: latest

python:
  # Install our python package before building the docs
  version: 3.8
  install:
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#  configuration: docs/source/conf.py